spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/transformer_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Local file storage configuration
file.upload-dir=./uploads/

# Retraining Service URL
trainer.service.url=${TRAINER_SERVICE_URL:http://localhost:8000/train}

